openapi: 3.0.0
info:
  title: API de prueba
  version: '1.0'
  contact:
    name: Fredy Rosero
    email: faroseroc@unal.edu.co
  description: Esta es una API de prueba para sincronizar su documentación con GitHub+Spotlight+Postman.
servers:
  - url: 'http://localhost:3000'
paths:
  '/libros/{isbn}':
    parameters:
      - schema:
          type: integer
          example: 9788497592208
          maximum: 9999999999999
          minimum: 1000000000
        name: isbn
        in: path
        required: true
    get:
      summary: Obtener un libro
      tags: []
      operationId: get-libros-isbn
      description: Obtener la info de un libro por su ISBN
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Libros'
              examples:
                Cien aÃ±os de soledad:
                  value:
                    ISBN: '9788497592208'
                    Nombre: One Hundred Years of Solitude
                    Autor:
                      id: 1
                      nombre: Gabriel Garcia Marquez
  /libros:
    get:
      summary: Obtener todos los libros
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Libros'
              examples:
                example-1:
                  value:
                    - ISBN: '9788497592208'
                      Nombre: One Hundred Years of Solitude
                    - ISBN: '1234567890'
                      Nombre: Mi Libro
      operationId: get-libros
      description: Obtener todos los libros
  '/autores/{idautor}':
    parameters:
      - schema:
          type: integer
        name: idautor
        in: path
        required: true
        description: El ID del autor
    get:
      summary: Obtener un autor
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Autores'
              examples:
                Gabo:
                  value:
                    id: 1
                    nombre: Gabriel Garcia Marquez
                Anom:
                  value:
                    id: 0
                    nombre: Anónimo
      operationId: get-autores-id_autor
      description: Obtener la info de un autor en particular
components:
  schemas:
    Libros:
      title: Libros
      type: object
      x-examples:
        Cien aÃ±os de soledad:
          ISBN: '9788497592208'
          Nombre: One Hundred Years of Solitude
          Autor:
            id: 1
            nombre: Gabriel Garcia Marquez
      properties:
        ISBN:
          type: string
        Nombre:
          type: string
        Autor:
          $ref: '#/components/schemas/Autores'
      description: ''
    Autores:
      title: Autores
      type: object
      properties:
        id:
          type: integer
          default: 0
        nombre:
          type: string
      description: ''
      x-examples:
        Gabo:
          id: 1
          nombre: Gabriel Garcia Marquez
        Anom:
          id: 2
          nombre: Anónimo
